<a href="https://colab.research.google.com/github/justdvnsh/Classification-Methods/blob/master/Classification/titanic/titanic_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df_train = pd.read_csv('https://raw.githubusercontent.com/justdvnsh/Classification-Methods/master/Classification/titanic/train.csv', delimiter=',')
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df_train.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_train.dropna(axis=0, inplace=True)
df_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch
0            1         0       3    male  22.0      1      0
1            2         1       1  female  38.0      1      0
2            3         1       3  female  26.0      0      0
3            4         1       1  female  35.0      1      0
4            5         0       3    male  35.0      0      0

In [4]:
df_train = pd.get_dummies(df_train, columns=['Sex'])
df_train.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0            1         0       3  22.0      1      0           0         1
1            2         1       1  38.0      1      0           1         0
2            3         1       3  26.0      0      0           1         0
3            4         1       1  35.0      1      0           1         0
4            5         0       3  35.0      0      0           0         1

In [5]:
X = df_train.iloc[:, 2:]
y = df_train.iloc[:, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
X_test

Pclass    Age  SibSp  Parch  Sex_female  Sex_male
423       3  28.00      1      1           1         0
177       1  50.00      0      0           1         0
305       1   0.92      1      2           0         1
292       2  36.00      0      0           0         1
889       1  26.00      0      0           0         1
595       3  36.00      1      1           0         1
637       2  31.00      1      1           0         1
54        1  65.00      0      1           0         1
456       1  65.00      0      0           0         1
110       1  47.00      0      0           0         1
287       3  22.00      0      0           0         1
315       3  26.00      0      0           1         0
691       3   4.00      0      1           1         0
811       3  39.00      0      0           0         1
861       2  21.00      1      0           0         1
15        2  55.00      0      0           1         0
239       2  33.00      0      0           0         1
644       3   0.75      2      1           1         0
394       3  24.00      0      2           1         0
795       2  39.00      0      0           0         1
131       3  20.00      0      0           0         1
346       2  40.00      0      0           1         0
9         2  14.00      1      0           1         0
477       3  29.00      1      0           0         1
606       3  30.00      0      0           0         1
469       3   0.75      2      1           1         0
325       1  36.00      0      0           1         0
72        2  21.00      0      0           0         1
724       1  27.00      1      0           0         1
40        3  40.00      1      0           1         0
..      ...    ...    ...    ...         ...       ...
395       3  22.00      0      0           0         1
882       3  22.00      0      0           1         0
821       3  27.00      0      0           0         1
314       2  43.00      1      1           0         1
622       3  20.00      1      1           0         1
204       3  18.00      0      0           0         1
60        3  22.00      0      0           0         1
731       3  11.00      0      0           0         1
81        3  29.00      0      0           0         1
676       3  24.50      0      0           0         1
433       3  17.00      0      0           0         1
378       3  20.00      0      0           0         1
174       1  56.00      0      0           0         1
624       3  21.00      0      0           0         1
642       3   2.00      3      2           1         0
157       3  30.00      0      0           0         1
427       2  19.00      0      0           1         0
698       1  49.00      1      1           0         1
179       3  36.00      0      0           0         1
24        3   8.00      3      1           1         0
630       1  80.00      0      0           0         1
458       2  50.00      0      0           1         0
49        3  18.00      1      0           1         0
539       1  22.00      0      2           1         0
267       3  25.00      1      0           0         1
352       3  15.00      1      1           0         1
99        2  34.00      1      0           0         1
689       1  15.00      0      1           1         0
858       3  24.00      0      3           1         0
137       1  37.00      1      0           0         1

[179 rows x 6 columns]

In [0]:
## Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB(priors=None)

In [9]:
y_pred = classifier.predict(X_test)
pred_df = pd.DataFrame({
    'y_test': y_test,
    'y_pred': y_pred
})
pred_df

y_pred  y_test
423       1       0
177       1       0
305       0       1
292       0       0
889       0       1
595       0       0
637       0       0
54        0       0
456       0       0
110       0       0
287       0       0
315       1       1
691       1       1
811       0       0
861       0       0
15        1       1
239       0       0
644       1       1
394       1       1
795       0       0
131       0       0
346       1       1
9         1       1
477       0       0
606       0       0
469       1       1
325       1       1
72        0       0
724       0       1
40        1       0
..      ...     ...
395       0       0
882       1       0
821       0       1
314       0       0
622       0       1
204       0       1
60        0       0
731       0       0
81        0       1
676       0       0
433       0       0
378       0       0
174       0       0
624       0       0
642       1       0
157       0       0
427       1       1
698       0       0
179       0       0
24        1       0
630       0       1
458       1       1
49        1       0
539       1       1
267       0       1
352       0       0
99        0       0
689       1       1
858       1       1
137       0       0

[179 rows x 2 columns]

In [10]:
score = accuracy_score(y_test, y_pred)
score

0.776536312849162

In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[87, 16],
       [24, 52]])

In [12]:
report = classification_report(y_test, y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.78      0.84      0.81       103
          1       0.76      0.68      0.72        76

avg / total       0.78      0.78      0.77       179



In [13]:
df_test = pd.read_csv('https://raw.githubusercontent.com/justdvnsh/Classification-Methods/master/Classification/titanic/test.csv', delimiter=',')
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [14]:
df_test.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_test.dropna(axis=0, inplace=True)
df_test = pd.get_dummies(df_test, columns=['Sex'])
df_test.head()

PassengerId  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0          892       3  34.5      0      0           0         1
1          893       3  47.0      1      0           1         0
2          894       2  62.0      0      0           0         1
3          895       3  27.0      0      0           0         1
4          896       3  22.0      1      1           1         0

In [15]:
X_test

array([[ 0.89707924, -0.11705424,  0.515219  ,  0.65287483,  1.33117269,
        -1.33117269],
       [-1.51466646,  1.4030636 , -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [-1.51466646, -1.9881811 ,  0.515219  ,  1.80184861, -0.75121734,
         0.75121734],
       ...,
       [-1.51466646, -1.01530569, -0.54088125,  0.65287483,  1.33117269,
        -1.33117269],
       [ 0.89707924, -0.3934393 , -0.54088125,  2.9508224 ,  1.33117269,
        -1.33117269],
       [-1.51466646,  0.50481215,  0.515219  , -0.49609896, -0.75121734,
         0.75121734]])

In [16]:
df_test.head()
df_test_passenger_id = df_test.iloc[:, 0]
df_test = df_test.iloc[:, 1:]
df_test.head()

Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0       3  34.5      0      0           0         1
1       3  47.0      1      0           1         0
2       2  62.0      0      0           0         1
3       3  27.0      0      0           0         1
4       3  22.0      1      1           1         0

In [17]:
df_test = sc.transform(df_test)
df_test

array([[ 0.89707924,  0.33207148, -0.54088125, -0.49609896, -0.75121734,
         0.75121734],
       [ 0.89707924,  1.1957748 ,  0.515219  , -0.49609896,  1.33117269,
        -1.33117269],
       [-0.30879361,  2.23221878, -0.54088125, -0.49609896, -0.75121734,
         0.75121734],
       ...,
       [ 0.89707924, -0.11705424, -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [-1.51466646,  0.64300468, -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [ 0.89707924,  0.60845655, -0.54088125, -0.49609896, -0.75121734,
         0.75121734]])

In [18]:
test_prediction = classifier.predict(df_test)
prediction_df = pd.DataFrame({
    'passenger_id': df_test_passenger_id,
    'Survived': test_prediction
})
prediction_df

Survived  passenger_id
0           0           892
1           1           893
2           0           894
3           0           895
4           1           896
5           0           897
6           1           898
7           0           899
8           1           900
9           0           901
11          0           903
12          1           904
13          0           905
14          1           906
15          1           907
16          0           908
17          0           909
18          1           910
19          1           911
20          0           912
21          0           913
23          0           915
24          1           916
25          0           917
26          1           918
27          0           919
28          0           920
30          0           922
31          0           923
32          1           924
..        ...           ...
381         0          1273
383         1          1275
385         1          1277
386         0          1278
387         0          1279
388         0          1280
389         0          1281
390         0          1282
391         1          1283
392         0          1284
393         0          1285
394         0          1286
395         1          1287
396         0          1288
397         1          1289
398         0          1290
399         0          1291
400         1          1292
401         0          1293
402         1          1294
403         0          1295
404         0          1296
405         0          1297
406         0          1298
407         0          1299
409         1          1301
411         1          1303
412         1          1304
414         1          1306
415         0          1307

[332 rows x 2 columns]

In [0]:
prediction_df.to_csv('predictions.csv', sep=',')